### ISSUE TITLE
Build fails because of transitive dependency

### ISSUE THREAD

**Issue by FRosner** [eeue56/elm-html-in-elm#10]
## Problem

My build suddenly failed today (18 July 2017) with the following error message:

```
$ elm-test 
Success! Compiled 119 modules.
Successfully generated /tmp/elm_test_117618-6873-q2aemp.5e8rxjemi.js
The test run failed because it encountered a runtime exception:
 ReferenceError: _eeue56$elm_html_in_elm$ElmHtml_ToString$nodeToStringWithOptions is not defined
    at eval (eval at <anonymous> (/home/travis/build/FRosner/cluster-broccoli/elm/node_modules/elm-test/bin/elm-test:119:32), <anonymous>:9542:66)
    at eval (eval at <anonymous> (/home/travis/build/FRosner/cluster-broccoli/elm/node_modules/elm-test/bin/elm-test:119:32), <anonymous>:26055:4)
    at /home/travis/build/FRosner/cluster-broccoli/elm/node_modules/elm-test/bin/elm-test:119:32
    at evalElmCode (/home/travis/build/FRosner/cluster-broccoli/elm/node_modules/elm-test/bin/elm-test:119:76)
    at /home/travis/build/FRosner/cluster-broccoli/elm/node_modules/elm-test/bin/elm-test:303:33
    at process._tickCallback (internal/process/next_tick.js:103:7)
error Command failed with exit code 2.
```

Looking into the details I discovered that elm-html-test (3.0.0) was pulling elm-html-in-elm (5.0.0) as a transitive dependency but now it was pulling a newer version (5.2.0). This most probably caused the error.

When I execute it locally it still pulls 5.0.0. Why is this happening?

## References

- [Failing Build](https://travis-ci.org/FRosner/cluster-broccoli/jobs/254744579#L537)
- [Succeeding Build](https://travis-ci.org/FRosner/cluster-broccoli/jobs/254490173#L535)

**Comment by eeue56** [comment]
Just delete elm-stuff and run elm-package install again. This is an issue with elm-package

**Comment by FRosner** [comment]
Thanks for your quick response!

I'm running it on Travis. Why is it getting the newer version suddenly? After I [fixed the version](https://github.com/FRosner/cluster-broccoli/commit/179a8162a5f7fd7f11bde20525d060d76943f5c3) it works now. Also, why does it fail with this version?

The expected behaviour is that I'm getting 5.0.0 so the build does not fail, no?

**Comment by FRosner** [comment]
Ok turns out we are indeed caching the elm-stuff folder. Do you have a reference to an issue in elm-package so I know when it is resolved?

Thanks for your support!

**Comment by eeue56** [comment]
@FRosner Can you try upgrading elm-html-test as well as elm-html-in-elm and see if it's still broken?

AFAIK this issue should only come up with a cached elm-stuff directory. If it comes up in another case, then there is something else wrong -- the error you are getting suggests that Elm's code is being generated incorrectly. Most of the time, this is down to invalid cache management. I'm not sure of any open issue, but this is less likely to be an issue in 0.19.

**Comment by FRosner** [comment]
I will try it later. Thanks!

**Comment by eeue56** [comment]
I believe this is fixed. Closing as a result
