### ISSUE TITLE
Create a release <2.1.0 to update elm-static-html command line tool

### ISSUE THREAD

**Issue by YetAnotherMinion** [eeue56/elm-html-in-elm#5]
**elm-static-html** hardcodes the version it expects.(https://github.com/eeue56/elm-static-html/blob/master/index.js#L155). The changes I made to support void elements should be made available to users of that tool by creating a release <2.1.0 of this repository.

**Comment by eeue56** [comment]
published as 2.1.0

**Comment by eeue56** [comment]
and I published elm-static-html as 1.3.2
